project:
  type: book
  output-dir: docs

book:
  title: "Analyzing Candian demographic and housing data using R"
  author: "Jens von Bergmann"
  date: "2022-04-01"
  chapters:
    - index.qmd
    - intro.qmd
    - part: intro_to_r.qmd
      chapters:
      - intro_cansim.qmd
      - intro_cancensus.qmd
    - part: basic.qmd
      chapters:
      - basic_bc_pop.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

