project:
  type: book
  output-dir: docs

book:
  title: "Analyzing Candian demographic and housing data using R"
  author: "Jens von Bergmann"
  date: "2022-04-01"
  chapters:
    - index.qmd
    - intro.qmd
    - part: intro_to_r/intro_to_r.qmd
      chapters:
      - intro_to_r/intro_cansim.qmd
      - intro_to_r/intro_cancensus.qmd
    - part: basic_descriptive/basic_descriptive.qmd
      chapters:
      - basic_descriptive/cars_vs_suvs.qmd
    - part: advanced_descriptive/advanced_descriptive.qmd
      chapters:
      - advanced_descriptive/advanced_descriptive_bc_migration.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

